version: '3.3'

services:
  nginx:
    image: nginx:1.18-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html:cached
      - ./.data/logs/nginx:/var/log/nginx
    ports:
      - 80:80
