version: '3.3'

services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - .:/usr/share/nginx/html:cached
      - ./.data/logs/nginx:/var/log/nginx:delegated
      - ./.data/cache/nginx:/var/cache/nginx:cached
      - ./.docker/nginx/templates:/etc/nginx/templates:cached
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']
